version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/" 
    schedule:
      interval: "daily"
    ignore:
      - dependency-name: "react"
        versions: ["18.3.1"]
      - dependency-name: "next"
        versions: ["15.3.3"]
  - package-ecosystem: "github-actions"
    directory: "/" 
    schedule:
      interval: "weekly"
